/**
 * Unified error categories that represent all error types
 */
export enum ErrorCategory {
  // Database errors
  DATABASE = 'DATABASE_ERROR',
  CONNECTION = 'CONNECTION_ERROR',
  QUERY = 'QUERY_ERROR',
  CONSTRAINT = 'CONSTRAINT_ERROR',
  TRANSACTION = 'TRANSACTION_ERROR',

  // API and network errors
  NETWORK = 'NETWORK_ERROR',
  HTTP_CLIENT = 'HTTP_CLIENT_ERROR',
  HTTP_SERVER = 'HTTP_SERVER_ERROR',
  TIMEOUT = 'TIMEOUT_ERROR',

  // Authentication and authorization
  AUTHENTICATION = 'AUTHENTICATION_ERROR',
  AUTHORIZATION = 'AUTHORIZATION_ERROR',

  // Resource errors
  NOT_FOUND = 'NOT_FOUND_ERROR',
  PERMISSION = 'PERMISSION_ERROR',
  CONFLICT = 'CONFLICT_ERROR',

  // UI and interaction errors
  UI = 'UI_ERROR',
  ELEMENT = 'ELEMENT_ERROR',
  NAVIGATION = 'NAVIGATION_ERROR',
  SELECTOR = 'SELECTOR_ERROR',
  ASSERTION = 'ASSERTION_ERROR',

  // Input/Output errors
  IO = 'IO_ERROR',
  PARSING = 'PARSING_ERROR',
  VALIDATION = 'VALIDATION_ERROR',
  SERIALIZATION = 'SERIALIZATION_ERROR',

  // Test execution errors
  TEST = 'TEST_ERROR',
  SETUP = 'SETUP_ERROR',
  TEARDOWN = 'TEARDOWN_ERROR',
  FIXTURE = 'FIXTURE_ERROR',
  EXPECTED_FAILURE = 'EXPECTED_FAILURE',

  // Performance and resource errors
  PERFORMANCE = 'PERFORMANCE_ERROR',
  MEMORY = 'MEMORY_ERROR',
  RESOURCE_LIMIT = 'RESOURCE_LIMIT_ERROR',

  // Environment errors
  ENVIRONMENT = 'ENVIRONMENT_ERROR',
  DEPENDENCY = 'DEPENDENCY_ERROR',

  // Service errors
  SERVICE = 'SERVICE_ERROR',
  CONFIGURATION = 'CONFIGURATION_ERROR',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED_ERROR',

  // File system errors
  FILE_NOT_FOUND = 'FILE_NOT_FOUND_ERROR', // ENOENT
  PATH_IS_DIRECTORY = 'PATH_IS_DIRECTORY_ERROR', // EISDIR
  NOT_A_DIRECTORY = 'NOT_A_DIRECTORY_ERROR', // ENOTDIR
  DIRECTORY_NOT_EMPTY = 'DIRECTORY_NOT_EMPTY_ERROR', // ENOTEMPTY
  FILE_EXISTS = 'FILE_EXISTS_ERROR', // EEXIST
  ACCESS_DENIED = 'ACCESS_DENIED_ERROR', // EACCES
  FILE_BUSY = 'FILE_BUSY_ERROR', // EBUSY
  FILE_TOO_LARGE = 'FILE_TOO_LARGE_ERROR', // EFBIG
  FILE_NAME_TOO_LONG = 'FILE_NAME_TOO_LONG_ERROR', // ENAMETOOLONG
  NO_SPACE = 'NO_SPACE_ERROR', // ENOSPC
  READ_ONLY_FILE_SYSTEM = 'READ_ONLY_FILE_SYSTEM_ERROR', // EROFS

  // Fallback
  UNKNOWN = 'UNKNOWN_ERROR',
}
